### PR TITLE
Add tket docs

### PR DESCRIPTION
**Pull request by isobelhooper**
Changes:
* Add placeholder index page and directory for tket docs
* Add entry to deploy_site.yml to fetch and extract the tket docs tarball.
* Update (temporary) landing page to include links to TKET site in nav bar and main flow.

### CODE REVIEW

**Comment by isobelhooper** [comment]
Deploys fine, but the tket landing page doesn't load some of its CSS and JS files. Aidan says this is because NextJS expects a baseURL parameter if it's deployed in a sub-path (this is deployed at `cqcl.github.io/quantinuum-docs/tket`, for example).

Have redeployed from main for now, and will keep this open for the moment.

**Comment by isobelhooper** [comment]
This will need rebasing before we merge it in, and now the base URL should be fixed at `docs.quantinuum.com/tket` we should be able to reconfigure NextJS's output without needing to change it once again.

**Review by aidanCQ — APPROVED** [review]

**Comment by aidanCQ** [comment]
Are we okay to merge this? @isobelhooper

**Comment by isobelhooper** [comment]
> Are we okay to merge this? @isobelhooper

Yup, we're good to merge. Examples and user manual don't have a nav bar but that's also the case on tket.quantinuum.com so there's no regression. Those can be updated in a later tket-site release.

**Comment by CalMacCQ** [comment]
Manual/examples updates are done - just waiting on a review for this https://github.com/CQCL/pytket-docs/pull/339

**Pull request merged**
